version: "3.7"

services:
  redis:
    image: redis
    hostname: redis-server
    restart: always
    ports:
      - "16379:6379"
    networks:
      - test_java

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "18001:8001"
    networks:
      - test_java

networks:
  test_java:
